### ISSUE TITLE
Gerbers

### ISSUE THREAD

**Issue by lafkyc** [botanicfields/BF-017#1]
Would you be willing to share gerbers? I would love to just have one made to play with in my lab

**Comment by uehara00** [comment]
I uploaded the gerber and kicad files(sch and pcb) now.
The board is sold at a market place in Japan.
https://www.switch-science.com/catalog/6433/
Please enjoy!

**Comment by lafkyc** [comment]
Thank you much! I have never seen that website before either looks cool :)
